//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerContactManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        
        public Customer()
        {
            this.Addresses = new HashSet<Address>();
        }
    
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string MobileNo { get; set; }
        public bool IsActive { get; set; }
        public string ImageUrl { get; set; }
        public decimal DepositeAmount { get; set; }
        public string Email { get; set; }
        public int CustomerTypeId { get; set; }
    
        
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual CustomerType CustomerType { get; set; }
    }
}
